apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wjyu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-wjyu@sha256:d070cc6330e174e1f84d67098f0deeb0e659e1cbd46f02253bc00b6f6057ce6f
        name: my-nodejs
        resources: {}
status: {}
